### ISSUE TITLE
<bundlesDirectory> ignored?

### ISSUE THREAD

**Issue by hannes-marais** [lgrignon/jsweet-maven-plugin#13]
I have not been able to get the <bundlesDirectory> to actually copy the bundle to the indicated directory. Perhaps I am missing something in my POM?  I also have the Eclipse plugin, and the two have the same output directory "dist", but it does not seem to work there either.

Am I missing something?  I literally just started playing around with JSweet today (and I am super excited), so I probably miss something.

Here is my POM for the record.  The bundle.js is always located in target/js

BTW is there anyway to rename the bundle?

Thanks, Hannes

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<groupId>jsweet-test</groupId>
	<artifactId>jsweet-test</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<repositories>

		<repository>
			<id>jsweet-central</id>
			<name>libs-release</name>
			<url>http://repository.jsweet.org/artifactory/libs-release-local</url>
		</repository>

		<repository>
			<snapshots />
			<id>jsweet-snapshots</id>
			<name>libs-snapshot</name>
			<url>http://repository.jsweet.org/artifactory/libs-snapshot-local</url>
		</repository>

	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<id>jsweet-plugins-release</id>
			<name>plugins-release</name>
			<url>http://repository.jsweet.org/artifactory/plugins-release-local</url>
		</pluginRepository>
		<pluginRepository>
			<snapshots />
			<id>jsweet-plugins-snapshots</id>
			<name>plugins-snapshot</name>
			<url>http://repository.jsweet.org/artifactory/plugins-snapshot-local</url>
		</pluginRepository>
	</pluginRepositories>

	<dependencies>

		<dependency>
			<groupId>org.jsweet.candies</groupId>
			<artifactId>jsweet-core</artifactId>
			<version>1.1.0-SNAPSHOT</version>
		</dependency>

	</dependencies>

	<build>
		<sourceDirectory>src</sourceDirectory>

		<plugins>

			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.3</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.jsweet</groupId>
				<artifactId>jsweet-maven-plugin</artifactId>
				<version>1.1.1</version>
				<configuration>
					<sourceMap>true</sourceMap>
					<outDir>target/js</outDir>
					<targetVersion>ES3</targetVersion>
					<verbose>true</verbose>
					<bundle>true</bundle>
					<bundlesDirectory>dist</bundlesDirectory>
				</configuration>

				<executions>
					<execution>
						<id>generate-js</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>jsweet</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

		</plugins>

		<pluginManagement>
			<plugins>
				
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>1.0.0</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>org.jsweet</groupId>
										<artifactId>jsweet-maven-plugin</artifactId>
										<versionRange>[1.1.0-SNAPSHOT,)</versionRange>
										<goals>
											<goal>jsweet</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<ignore></ignore>
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>
			</plugins>
	</pluginManagement>
	
	</build>
</project>

**Comment by renaudpawlak** [comment]
Actually I don't think that you are missing anything. It is JSweet's fault because it ignores the bundle directory since version 1.1. Actually I think that the bundle directory should be deprecated/removed because you can simply use the ``outDir`` option to put the bundle wherever you want. The best way to do it is to set the ``outDir`` to follow the webjars conventions so that JSweet can automatically extract the bundle in the client Maven projet.

Here is how we use the bundle option:

```xml
			<plugin>
				<groupId>org.jsweet</groupId>
				<artifactId>jsweet-maven-plugin</artifactId>
				<version>1.2.0-SNAPSHOT</version>
				<configuration>
					<bundle>true</bundle>
					<outDir>src/main/resources/META-INF/resources/webjars/${project.name}/${project.version}</outDir>
					<tsOut>.jsweet/ts</tsOut>
					<targetVersion>ES5</targetVersion>
					<verbose>true</verbose>
					<declaration>true</declaration>
					<dtsOut>src/main/resources/src/typings</dtsOut>
					<encoding>UTF-8</encoding>
				</configuration>
				<executions>
					<execution>
						<id>generate-js</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>jsweet</goal>
						</goals>
					</execution>
					<execution>
						<id>clean</id>
						<phase>clean</phase>
						<goals>
							<goal>clean</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```

In that case, the bundle will be packaged in the jar by Maven (because it is in the resource directory). In the client Maven project you can extract the bundle in a specific directory with the following configuration:

```xml
	<candiesJsOut>src/main/webapp/js/candies</candiesJsOut>
```

Currently there is no way to set the bundle name, so we discriminate with the directory name (``${project.name}/${project.version}``). 

Do not hesitate to tell us if your use case requires specific configuration that we could support in the snapshot version.
