### ISSUE TITLE
Command line to long error on windows machines

### ISSUE THREAD

**Issue by mirkosertic** [lgrignon/jsweet-maven-plugin#14]
I am using a windows box with JSweet 1.2.0-SNAPSHOT and i am getting an exception during compilation of a project with a few hundred files. It seems that the generated tsc command line is too long. Running the same build on a windows machine is just fine.

**Comment by lgrignon** [comment]
Hello, did you try putting your project in your virtual drive's root. It would only be a workaround but it's worth trying.

Thanks for reporting.

**Comment by renaudpawlak** [comment]
Could you send the full stacktrace to check whether it is a Maven plugin issue or a JSweet issue?
Txs

**Comment by lgrignon** [comment]
Hello @mirkosertic, any news on this point? Otherwise I close the issue.
