### ISSUE TITLE
CompletionFailure error trace

### ISSUE THREAD

**Issue by renaudpawlak** [lgrignon/jsweet-maven-plugin#2]
On examples, I get:

com.sun.tools.javac.code.Symbol$CompletionFailure: class file for jsweet.util.StringTypes$StringTypes$currency not found
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for jsweet.util.StringTypes$StringTypes$number not found
(...)

These messages do not appear with the command line launcher. Probably because of a classpath difference in Maven.

**Comment by lgrignon** [comment]
@renaudpawlak I didn't try on V2 examples, still an issue?

**Comment by renaudpawlak** [comment]
I haven't noticed in a long time. So I think we can close this one :)
