### ISSUE TITLE
Test classes conversion

### ISSUE THREAD

**Issue by isakovarseniy** [lgrignon/jsweet-maven-plugin#31]
Hi 
Is it possible to covert test classes?  I have tried to use <includes> but seems like it undersent only **/*.java. If I put something like src/test/java/\*\*/\*.java transplanter ignores everything

Thanks
Arseniy Isakov

**Comment by lgrignon** [comment]
Hi @isakovarseniy 
You can include your unit test sources using the <includes> option of the JSweet maven plugin.
The node example shows an example use case:
https://github.com/lgrignon/jsweet-node-example/blob/master/pom.xml#L39

Please close this issue if this suits your need

**Comment by isakovarseniy** [comment]
Thanks
