### ISSUE TITLE
Feature request: Extra Path config for node.js installation

### ISSUE THREAD

**Issue by philwilkinson** [lgrignon/jsweet-maven-plugin#33]
I would like to be able to configure the node.js path in maven, so that jsweet can find a node.js installation installed by https://github.com/eirslett/frontend-maven-plugin.
see https://github.com/cincheo/jsweet/issues/347 for  (gradle specific) details.
Once jsweet has exposed EXTRA_PATH, expose the extraPath configuration property to the maven build.

**Comment by lgrignon** [comment]
I added this to the maven plugin because I add to fix something inside it, if you want to review:
389198a86f0d168bb4c176d4c9bd9b2f761c9894

Same principle as for Gradle plugin, we use ProcessUtil directly but in the future we may go through JSweet config, it would make sense

**Comment by lgrignon** [comment]
@philwilkinson could you check and close issue of ok for you please?

**Comment by philwilkinson** [comment]
Perfect. Now with jsweet-maven-plugin version 2.0.0-SNAPSHOT I can add
```
<configuration>
    ...
    <extraSystemPath>C:\Data\Phil\Dev\jsweet-examples\.gradle\nodejs\node-v8.2.1-win-x64</extraSystemPath>
</configuration>
```
To the [jsweet-examples pom](https://github.com/cincheo/jsweet-examples/blob/master/pom.xml) and now `mvn install` will use my builds locally installed node.js (installed previously in gradle build). Which is exacly what I wanted. Thanks.
