### ISSUE TITLE
Generated sourceMap contains windows path and unnecessary sourceRoot

### ISSUE THREAD

**Issue by balazs-zsoldos** [lgrignon/jsweet-maven-plugin#39]
The generated sourceMap is next to the JS file and it has a content like the following:

    {
      "version":3,
      "file":"AnotherClass.js",
      "lineCount":20,
      "sourceRoot":"..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\src\\main\\java/",
      "mappings":"AAEA,kE;AAAA,O;AAAA,gB;AAAA,iB;AAAA,0B;AAAA,e;AAAA,wB;AAAA,4B;AAAA,qC;AAAA,sB;AAAA,+B;AAAA,oD;AAAA,gD;;AAEA,wE;AACA,mD;AACA,yB;;;AAJA;",
      "sources":["com\\libmarket\\web\\webresources\\js\\AnotherClass.java"],
      "names":[]
    }

My problems are the following:

 - For me sourceRoot seems to be unnecessary if I copy the Java files into the target JAR file next to the JS files. I could not find a way to delete it. The best I could do is set a ".", however, I am not sure it is the right solution.
 - The sources do not have to contain a path at all, only the file name. Even worse, that the source path contains Windows path separators if the compilation is done on windows

A sourceMap I would expect would look like the following:

    {
      "version":3,
      "file":"AnotherClass.js",
      "lineCount":20,
      "mappings":"AAEA,kE;AAAA,O;AAAA,gB;AAAA,iB;AAAA,0B;AAAA,e;AAAA,wB;AAAA,4B;AAAA,qC;AAAA,sB;AAAA,+B;AAAA,oD;AAAA,gD;;AAEA,wE;AACA,mD;AACA,yB;;;AAJA;",
      "sources":["AnotherClass.java"],
      "names":[]
    }

**Comment by lgrignon** [comment]
Hello, thanks for your feedback!
Your issue is rather a https://github.com/cincheo/jsweet issue since source map generation is handled in this project.
Would you want to add this contribution to the project?

**Comment by balazs-zsoldos** [comment]
I started to investigate a bit deeper. I could not find the right setting for tsc yet (I am very busy so it might take weeks). However, this has to be solved indeed inside jsweet first, and probably extra parameters can be introduced here later. I am closing the issue until this is solved on jsweet (or tsc) side.
