### ISSUE TITLE
'factoryClassPath' Option Does Not Work for Custom Factory

### ISSUE THREAD

**Issue by pbtura** [lgrignon/jsweet-maven-plugin#40]
Currently, the 'factoryClassPath' option in configuration only works for classes in jars included as dependencies of the jsweet-maven-plugin. If a custom JSweetFactory is defined within the project we are generating sources for, the generation will fail with a "cannot find or instantiate factory class" error.

**Comment by pbtura** [comment]
Here is the git: [https://github.com/pbtura/bigjsExample](https://github.com/pbtura/bigjsExample)
The custom factory is in the 'util' package.

**Comment by lgrignon** [comment]
Thanks. Indeed this is not possible since your class isn't compiled yet (at generate-sources time). I do not think this is standard in the Maven world to load class from the target project in a plugin mojo. I would recommend packaging your factory in an external JAR unless you recommend something better for loading project classes in the JSweet mojo.
However I agree that it would be very nice & straightforward to have this working.

Please tell me you thoughts or close issue if you don't think to a suggestion about it.

**Comment by pbtura** [comment]
I see what you mean about not having the compiled factory class. If that is the only obstacle however, there is a way around it. By adding an execution to the maven-compiler-plugin, we can force it to compile the factory class before the generator plugin is run. So for the example I posted you would have something like this:

```
<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
					<fork>true</fork>
					<includes>
						<include>**/util/TuraJSweetFactory.java</include>
					</includes>
				</configuration>
				<executions>
					<execution>
						<id>generate-factory</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>compile</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```

As long as the maven-compiler plugin is placed before the generator plugin, and as long as both target the same phase (generate-sources) then the factory will be compiled and ready by the time it is needed in the plugin.

**Comment by lgrignon** [comment]
This seems kind of hacky to me but we could make this work indeed. Do you want to give it a try and PR? I won't have time this week-end for this :/

**Comment by pbtura** [comment]
I finally go a chance to do some work on this and I think I have come up with a workable solution. I added a PR here: [https://github.com/lgrignon/jsweet-maven-plugin/pull/42](https://github.com/lgrignon/jsweet-maven-plugin/pull/42). Take a look when you get a chance and let me know what you think.

**Comment by lgrignon** [comment]
Fixed, thanks to PR https://github.com/lgrignon/jsweet-maven-plugin/pull/42

Thanks a lot to @pbtura

**Comment by pbtura** [comment]
Have you tried running the example project for your build? I'm seeing some
issues that are preventing source generation after I switched from my local
build to the updated 2.2.0-SNAPSHOT. There is some sort of issue with the
getCandiesJars() method of AbstractJsweetMojo. I'm not sure if it is
something with my setup or if it an actual bug. Let me know if you are
seeing issues with that code or not.

**Comment by lgrignon** [comment]
I tried to transpile https://github.com/pbtura/bigjsExample/blob/maven-plugin-demo/pom.xml
and
https://github.com/cincheo/jsweet-examples.git

Did you try cleaning your local repo (at least for org.jsweet group)

**Comment by pbtura** [comment]
I tried that with no luck. I posted a bug report here: [https://github.com/lgrignon/jsweet-maven-plugin/issues/43](https://github.com/lgrignon/jsweet-maven-plugin/issues/43) with more details.
