### ISSUE TITLE
it doesn't like the word "plugin"

### ISSUE THREAD

**Issue by skiwheelr** [lgrignon/jsweet-maven-plugin#44]
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM /Users/Terrapin/IdeaProjects/help/pom.xml: Unrecognised tag: 'plugin' (position: START_TAG seen ...</dependency>\n\n    <plugin>... @36:13)  @

**Comment by skiwheelr** [comment]
Got this far:

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.tutor</groupId>
    <artifactId>help</artifactId>
    <version>1.0-SNAPSHOT</version>

    <pluginRepositories>
        <pluginRepository>
            <id>jsweet-plugins-release</id>
            <name>plugins-release</name>
            <url>http://repository.jsweet.org/artifactory/plugins-release-local</url>
        </pluginRepository>
        <pluginRepository>
            <snapshots />
            <id>jsweet-plugins-snapshots</id>
            <name>plugins-snapshot</name>
            <url>http://repository.jsweet.org/artifactory/plugins-snapshot-local</url>
        </pluginRepository>
    </pluginRepositories>

    <build>
    <sourceDirectory>src</sourceDirectory>
    </build>

<dependencies>
    <dependency>
        <groupId>org.jsweet.candies</groupId>
        <artifactId>angular</artifactId>
        <version>1.4.1-SNAPSHOT</version>
    </dependency>
</dependencies>

        <groupId>org.jsweet</groupId>
        <artifactId>jsweet-maven-plugin</artifactId>
        <version>1.2.0-SNAPSHOT</version>
        <configuration>
            <outDir>javascript</outDir>
            <targetVersion>ES3</targetVersion>
        </configuration>
        <executions>
            <execution>
                <id>generate-js</id>
                <phase>generate-sources</phase>
                <goals>
                    <goal>org.jsweet</goal>
                </goals>
            </execution>
        </executions>




</project>

**Comment by lgrignon** [comment]
Hello @skiwheelr 
Your pom.xml seemed to be wrong.

Please, try to clone and run
https://github.com/cincheo/jsweet-quickstart

And use Maven 3.6 / JDK 8

Thanks!
