### ISSUE TITLE
ExceptionInInitializerError

### ISSUE THREAD

**Issue by devnewton** [lgrignon/jsweet-maven-plugin#49]
The following exception is raised by this plugin:

> Execution generate-js of goal org.jsweet:jsweet-maven-plugin:2.3.5:jsweet failed: An API incompatibility was encountered while executing org.jsweet:jsweet-maven-plugin:2.3.5:jsweet: java.lang.ExceptionInInitializerError: null
> [ERROR] -----------------------------------------------------
> [ERROR] realm =    plugin>org.jsweet:jsweet-maven-plugin:2.3.5
> [ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
> [ERROR] urls[0] = file:/C:/Users/devnewton/.m2/repository/org/jsweet/jsweet-maven-plugin/2.3.5/jsweet-maven-plugin-2.3.5.jar
> [ERROR] urls[1] = file:/C:/Users/devnewton/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
> [ERROR] urls[2] = file:/C:/Users/devnewton/.m2/repository/org/codehaus/plexus/plexus-utils/3.1.0/plexus-utils-3.1.0.jar
> [ERROR] urls[3] = file:/C:/Users/devnewton/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.24/plexus-interpolation-1.24.jar
> [ERROR] urls[4] = file:/C:/Users/devnewton/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.4/plexus-sec-dispatcher-1.4.jar
> [ERROR] urls[5] = file:/C:/Users/devnewton/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
> [ERROR] urls[6] = file:/C:/Users/devnewton/.m2/repository/org/apache/maven/maven-builder-support/3.5.3/maven-builder-support-3.5.3.jar
> [ERROR] urls[7] = file:/C:/Users/devnewton/.m2/repository/org/apache/maven/resolver/maven-resolver-util/1.1.1/maven-resolver-util-1.1.1.jar
> [ERROR] urls[8] = file:/C:/Users/devnewton/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.2.1/maven-shared-utils-3.2.1.jar
> [ERROR] urls[9] = file:/C:/Users/devnewton/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.3/org.eclipse.sisu.inject-0.3.3.jar
> [ERROR] urls[10] = file:/C:/Users/devnewton/.m2/repository/com/google/inject/guice/4.0/guice-4.0-no_aop.jar
> [ERROR] urls[11] = file:/C:/Users/devnewton/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
> [ERROR] urls[12] = file:/C:/Users/devnewton/.m2/repository/com/google/guava/guava/20.0/guava-20.0.jar
> [ERROR] urls[13] = file:/C:/Users/devnewton/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.7.1/plexus-component-annotations-1.7.1.jar
> [ERROR] urls[14] = file:/C:/Users/devnewton/.m2/repository/org/jsweet/jsweet-transpiler/2.3.5/jsweet-transpiler-2.3.5.jar
> [ERROR] urls[15] = file:/C:/Users/devnewton/.m2/repository/org/apache/commons/commons-text/1.3/commons-text-1.3.jar
> [ERROR] urls[16] = file:/C:/Users/devnewton/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar
> [ERROR] urls[17] = file:/C:/Users/devnewton/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar
> [ERROR] urls[18] = file:/C:/Users/devnewton/.m2/repository/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
> [ERROR] urls[19] = file:/C:/Users/devnewton/.m2/repository/com/martiansoftware/jsap/2.1/jsap-2.1.jar
> [ERROR] urls[20] = file:/C:/Users/devnewton/.m2/repository/com/google/javascript/closure-compiler/v20161201/closure-compiler-v20161201.jar
> [ERROR] urls[21] = file:/C:/Users/devnewton/.m2/repository/com/google/javascript/closure-compiler-externs/v20161201/closure-compiler-externs-v20161201.jar
> [ERROR] urls[22] = file:/C:/Users/devnewton/.m2/repository/args4j/args4j/2.33/args4j-2.33.jar
> [ERROR] urls[23] = file:/C:/Users/devnewton/.m2/repository/com/google/protobuf/protobuf-java/3.0.2/protobuf-java-3.0.2.jar
> [ERROR] urls[24] = file:/C:/Users/devnewton/.m2/repository/com/google/code/findbugs/jsr305/3.0.1/jsr305-3.0.1.jar
> [ERROR] urls[25] = file:/C:/Users/devnewton/.m2/repository/com/google/jsinterop/jsinterop-annotations/1.0.0/jsinterop-annotations-1.0.0.jar
> [ERROR] urls[26] = file:/C:/Users/devnewton/.m2/repository/org/jsweet/ext/typescript.java-ts.core/1.4.0.1/typescript.java-ts.core-1.4.0.1.jar
> [ERROR] urls[27] = file:/C:/Users/devnewton/.m2/repository/com/eclipsesource/minimal-json/minimal-json/0.9.4/minimal-json-0.9.4.jar
> [ERROR] urls[28] = file:/C:/Users/devnewton/.m2/repository/org/tukaani/xz/1.8/xz-1.8.jar
> [ERROR] urls[29] = file:/C:/Users/devnewton/.m2/repository/org/apache/commons/commons-lang3/3.7/commons-lang3-3.7.jar
> [ERROR] Number of foreign imports: 1
> [ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
>

**Comment by lgrignon** [comment]
Which Java and Maven version are you using please?

**Comment by lgrignon** [comment]
Hello, thanks for reporting but Java 11 is not supported yet, but there is currently a project to port JSweet from J8 to J11: 
https://github.com/cincheo/jsweet/issues/519
