### ISSUE TITLE
How to use include exclude option

### ISSUE THREAD

**Issue by frankcapodanno** [lgrignon/jsweet-maven-plugin#52]
In my Project (with the Maven Plugin) I want to transpile and  ignore some dependencies and some classes because it would be builded at runtime after a webservice was called 

I used <include> and <exclude> parameters and also <ignoredProblems> but at the end the transpilier says always that  

Ignored Problem that I used was : INTERNAL_JAVA_ERROR,INTERNAL_TRANSPILER_ERROR,INTERNAL_TSC_ERROR,MAPPED_TSC_ERROR

```
package de.example.not_core does not exist
import de.example.not_core;
                                                                             ^
2020-08-07 11:07:30.030 ERROR JSweetTranspiler:95 - C:\example\src\main\java\de\example\Example.java:31: error: cannot find symbol
```
I read the documentation but I'm a little bit confused. I don't understand if is possibile or not partially transpilation.

**Comment by lgrignon** [comment]
Hello,
Did you take a look at the "excludes" parameter?

**Comment by lgrignon** [comment]
You will find an example here: https://github.com/lgrignon/jsweet-maven-plugin#advanced-configuration

Can we close this please?

**Comment by frankcapodanno** [comment]
Thank you. I have resolved but I need to make some refractory. It's possibile to make partially transpilation when the classes have not too much compositional relantionships. Divide the logic with Pojo was possibile to make the transpilation. The problem was just from ts --> js. We can see that is resolved. There is different ways to resolve this problem
