### ISSUE TITLE
Is Java 11 supported?

### ISSUE THREAD

**Issue by raftAtGit** [lgrignon/jsweet-maven-plugin#55]
Hi there,

Is Java 11 supported? If so how?

I got the error below when trying to use `jsweet-maven-plugin` with Java 11?
```
2020-11-10 19:57:39.039 ERROR JSweetConfig:149 - class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
```

In [this issue](https://github.com/lgrignon/jsweet-maven-plugin/issues/45) it's mentioned JSweet does not support  Java > 8, but this is not the case anymore according to this [JSweet issue](https://github.com/cincheo/jsweet/issues/519)

**Comment by lgrignon** [comment]
Indeed, JSweet 3 supports Java 11.

Please take a look at those examples (both JSweet maven & gradle plugins are shown): 
https://github.com/cincheo/jsweet-examples/tree/JSweet3.0

Please close this issue if you made it work

**Comment by raftAtGit** [comment]
thanks for the pointer :)

I made it work, but I noticed some odd behavior. Gradle plugin does not work with Gradle 6.x versions, it needs 5.x version. I will create an issue for that in gradle plugin repo.

**Comment by lgrignon** [comment]
Actually, please try 3.0.0-RC11 it should work :)
